version: '3.7'

services:

  nova_showcase_dev:
    container_name: nova_showcase_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4002:80'