version: '3.9'
services:
  try_aut_web: 
    container_name: try_aut_web
    image: try_aut_web
    build: ./

  try_aut_nginx:
    container_name: try_aut_nginx
    image: try_aut_nginx
    build: ./nginx
    ports:
      - 3001:9080

networks:
  try_aut: