name: Deployment Prod

on:
  push:
    branches:
      - mainnet

jobs:
  build-and-deploy:
    name: Build and Deployment
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
      # Deploy to Server
      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MAINNET_FRONTEND_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.FRONTEND_SSH_KEY }}
          script: |
            #!/usr/bin/env bash

            cd Hub
            sudo git checkout mainnet;
            sudo git pull origin mainnet;

            sudo docker-compose stop hub_mainnet
            sudo docker rmi $(sudo docker images -f "dangling=true" -q) || true
            sudo docker-compose up --build hub_mainnet -d

            exit 0;