name: Deployment Prod

on: workflow_dispatch

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        env: 
          REPO_URL: ${{ github.repositoryUrl }}
          REPO_NAME: ${{ github.repository }}
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            #!/usr/bin/env bash

            # REPO_URL=$REPO_URL
            # REPO_NAME=$REPO_NAME
            # # Get name of repo and use it for directory name ex: owner/repo-name becomes -> repo-name
            # DIR_NAME=$(echo "$REPO_NAME" | cut -d '/' -f 2-)
            DIR_NAME='nova-showcase'
            TARGET='main'


            # if [ ! -d $DIR_NAME ]
            # then
            #     sudo git clone $REPO_URL
            # fi

            cd ~/$DIR_NAME || exit
            sudo chmod -R a+rwX .

            ACTION='\033[1;90m'
            NOCOLOR='\033[0m'

            # Checking if we are on the main branch

            echo -e ${ACTION}Checking Git repo
            BRANCH=$(git rev-parse --abbrev-ref HEAD)
            if [ "$BRANCH" != ${TARGET} ]
            then
              exit 0
            fi

            # Checking if the repository is up to date.

            git fetch
            HEADHASH=$(git rev-parse HEAD)
            UPSTREAMHASH=$(git rev-parse ${TARGET}@{upstream})

            if [ "$HEADHASH" == "$UPSTREAMHASH" ]
            then
              echo -e "${FINISHED}"Current branch is up to date with origin/${TARGET}."${NOCOLOR}"
              exit 0
            fi

            # If that's not the case, we pull the latest changes and we build a new image

            sudo git pull origin main;

            # Docker
            docker-compose -f docker-compose.prod.yml down
            docker rmi $(docker images -f "dangling=true" -q)
            docker-compose -f docker-compose.prod.yml up -d --build

            exit 0;
