name: Deployment Prod

on:
  push:
    branches:
      - mainnet
  workflow_dispatch:
    inputs:
      env_file:
        description: 'Environment file to use (e.g., .env, .env_prod)'
        required: true
        default: '.env_prod'

jobs:
  build-and-deploy:
    name: Build and Deployment
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
      # Deploy to Server
      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.FRONTEND_SSH_KEY }}
          script: |
            #!/usr/bin/env bash

            cd nova-showcase
            sudo git checkout mainnet;
            sudo git pull origin mainnet;

            sudo docker build -t autlabs/hub:mainnet . --build-arg ENV_FILE=.env
            # sudo docker push autlabs/hub:mainnet

            echo "Stopping and removing specific service: hub_mainnet"
            sudo docker-compose stop hub_mainnet
            sudo docker-compose rm -f hub_mainnet

            echo "Removing dangling images"
            sudo docker rmi $(sudo docker images -f "dangling=true" -q) || true

            echo "Pulling the new image"
            # sudo docker-compose pull hub_mainnet
            docker-compose up -d --build hub_mainnet

            exit 0;